/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index.route'
import { Route as PokemonIndexRouteImport } from './routes/pokemon.index.route'
import { Route as OrdersIndexRouteImport } from './routes/orders/index.route'
import { Route as CrazySearchParamsIndexRouteImport } from './routes/crazy-search-params.index.route'
import { Route as PokemonPokemonNameIndexRouteImport } from './routes/pokemon.$pokemonName.index.route'
import { Route as OrdersOrderIdIndexRouteImport } from './routes/orders/$orderId/index.route'
import { Route as OrdersOrderIdLineItemsIndexRouteImport } from './routes/orders/$orderId/line-items/index.route'
import { Route as OrdersOrderIdLineItemsLineItemIdIndexRouteImport } from './routes/orders/$orderId/line-items/$lineItemId/index.route'

// Create/Update Routes

const IndexRouteRoute = IndexRouteImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonIndexRouteRoute = PokemonIndexRouteImport.update({
  path: '/pokemon/',
  getParentRoute: () => rootRoute,
} as any)

const OrdersIndexRouteRoute = OrdersIndexRouteImport.update({
  path: '/orders/',
  getParentRoute: () => rootRoute,
} as any)

const CrazySearchParamsIndexRouteRoute =
  CrazySearchParamsIndexRouteImport.update({
    path: '/crazy-search-params/',
    getParentRoute: () => rootRoute,
  } as any)

const PokemonPokemonNameIndexRouteRoute =
  PokemonPokemonNameIndexRouteImport.update({
    path: '/pokemon/$pokemonName/',
    getParentRoute: () => rootRoute,
  } as any)

const OrdersOrderIdIndexRouteRoute = OrdersOrderIdIndexRouteImport.update({
  path: '/orders/$orderId/',
  getParentRoute: () => rootRoute,
} as any)

const OrdersOrderIdLineItemsIndexRouteRoute =
  OrdersOrderIdLineItemsIndexRouteImport.update({
    path: '/orders/$orderId/line-items/',
    getParentRoute: () => rootRoute,
  } as any)

const OrdersOrderIdLineItemsLineItemIdIndexRouteRoute =
  OrdersOrderIdLineItemsLineItemIdIndexRouteImport.update({
    path: '/orders/$orderId/line-items/$lineItemId/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/crazy-search-params/': {
      id: '/crazy-search-params/'
      path: '/crazy-search-params'
      fullPath: '/crazy-search-params'
      preLoaderRoute: typeof CrazySearchParamsIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/pokemon/': {
      id: '/pokemon/'
      path: '/pokemon'
      fullPath: '/pokemon'
      preLoaderRoute: typeof PokemonIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/orders/$orderId/': {
      id: '/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/pokemon/$pokemonName/': {
      id: '/pokemon/$pokemonName/'
      path: '/pokemon/$pokemonName'
      fullPath: '/pokemon/$pokemonName'
      preLoaderRoute: typeof PokemonPokemonNameIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/orders/$orderId/line-items/': {
      id: '/orders/$orderId/line-items/'
      path: '/orders/$orderId/line-items'
      fullPath: '/orders/$orderId/line-items'
      preLoaderRoute: typeof OrdersOrderIdLineItemsIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/orders/$orderId/line-items/$lineItemId/': {
      id: '/orders/$orderId/line-items/$lineItemId/'
      path: '/orders/$orderId/line-items/$lineItemId'
      fullPath: '/orders/$orderId/line-items/$lineItemId'
      preLoaderRoute: typeof OrdersOrderIdLineItemsLineItemIdIndexRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteRoute,
  CrazySearchParamsIndexRouteRoute,
  OrdersIndexRouteRoute,
  PokemonIndexRouteRoute,
  OrdersOrderIdIndexRouteRoute,
  PokemonPokemonNameIndexRouteRoute,
  OrdersOrderIdLineItemsIndexRouteRoute,
  OrdersOrderIdLineItemsLineItemIdIndexRouteRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/crazy-search-params/",
        "/orders/",
        "/pokemon/",
        "/orders/$orderId/",
        "/pokemon/$pokemonName/",
        "/orders/$orderId/line-items/",
        "/orders/$orderId/line-items/$lineItemId/"
      ]
    },
    "/": {
      "filePath": "index.route.tsx"
    },
    "/crazy-search-params/": {
      "filePath": "crazy-search-params.index.route.tsx"
    },
    "/orders/": {
      "filePath": "orders/index.route.tsx"
    },
    "/pokemon/": {
      "filePath": "pokemon.index.route.tsx"
    },
    "/orders/$orderId/": {
      "filePath": "orders/$orderId/index.route.tsx"
    },
    "/pokemon/$pokemonName/": {
      "filePath": "pokemon.$pokemonName.index.route.tsx"
    },
    "/orders/$orderId/line-items/": {
      "filePath": "orders/$orderId/line-items/index.route.tsx"
    },
    "/orders/$orderId/line-items/$lineItemId/": {
      "filePath": "orders/$orderId/line-items/$lineItemId/index.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
